# This file was generated by GoReleaser. DO NOT EDIT.
cask "mailwizz-cli" do
  version "1.0.3"

  on_macos do
    on_intel do
      sha256 "275219a402be26965cd16a869ed2868514277a2732be07d5a11d0c4e9afd289c"
      url "https://github.com/onetwist-software/mailwizz-cli/releases/download/v#{version}/mailwizz-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "13e44d5409d5d0ab5090ce522083066120e9343af93e45fecb0abee9c5dab70b"
      url "https://github.com/onetwist-software/mailwizz-cli/releases/download/v#{version}/mailwizz-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d337de3ef60e6f000ef3edf92b02311c64a1a7e87f0bf16f806267c146acfb7e"
      url "https://github.com/onetwist-software/mailwizz-cli/releases/download/v#{version}/mailwizz-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ca2c28d7ab187fe2bf0ca522a19e0288df4ca5e262845a4ed94fb6f099dea8b1"
      url "https://github.com/onetwist-software/mailwizz-cli/releases/download/v#{version}/mailwizz-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mailwizz-cli"
  desc "CLI client for the MailWizz REST API"
  homepage "https://github.com/onetwist-software/mailwizz-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mailwizz-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mailwizz-cli"]
    end
  end

  # No zap stanza required

end
