# This file was generated by GoReleaser. DO NOT EDIT.
cask "mailwizz-cli" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "d36ff9dd82529bdd54ba2be7aadc769c87b6deb6d89f8d187fbcdd6aa1f6a6c8"
      url "https://github.com/onetwist-software/mailwizz-cli/releases/download/v#{version}/mailwizz-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2535e392cfc4914dba8dc9fd7794ad27ac615368bbfb27c2d653bab7eb54af0a"
      url "https://github.com/onetwist-software/mailwizz-cli/releases/download/v#{version}/mailwizz-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e78c87ee97684b2e165b2f4ac7c62287ebd9a863b3e3e71719b5ac875056caef"
      url "https://github.com/onetwist-software/mailwizz-cli/releases/download/v#{version}/mailwizz-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "99980affad20eca5368633b9cb0941fe3e301f7e6ebd2c0a812afd9ce909c223"
      url "https://github.com/onetwist-software/mailwizz-cli/releases/download/v#{version}/mailwizz-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mailwizz-cli"
  desc "CLI client for the MailWizz REST API"
  homepage "https://github.com/onetwist-software/mailwizz-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mailwizz-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mailwizz-cli"]
    end
  end

  # No zap stanza required

end
